from enum import Enum, unique


@unique
class ErrorCodes(Enum):
    REQUEST_VALIDATION_FAILED = 'VE400'
    MULTIPLE_OBJECTS_FOUND_UNEXPECTED = 'VE500'
    RESOURCE_DUPLICATION = 'PO400'
    RESOURCE_DUPLICATION_ATTEMPTED = 'VE210'
    POST_NOT_FOUND = 'PO404'
    MULTIPLE_POSTS_FOUND = 'PO409'
    INTERNAL_SERVER_ERROR = 'IS500'
    DATABASE_OPERATION_ERROR = 'PO111'
    RESPONSE_DATA_NOT_CORRECT = 'PO500'
    POST_UPDATION_ERROR = 'PO501'
    METHOD_NOT_ALLOWED = "PO405"
    GATEWAY_TIMEOUT = 'PO205'
    LARGE_STRING = "P0413"
